##cam_width 和 cam_height 表示图像的宽度和高度，
##cam_fx 和 cam_fy 是相机的焦距，
##cam_cx 和 cam_cy 是相机光心在图像平面上的坐标，
##cam_d0、cam_d1、cam_d2 和 cam_d3 是相机的畸变参数

#k1 对应 cam_d0，是相机的径向畸变高阶项系数之一
#k2 对应 cam_d1，是相机的径向畸变高阶项系数之一
#p1 对应 cam_d2，是相机的切向畸变系数之一
#p2 对应 cam_d3，是相机的切向畸变系数之一

cam_model: Pinhole

cam_width: 1280
cam_height: 1024

scale: 0.5

cam_fx: 1293.56944
cam_fy: 1293.3155

cam_cx: 626.91359
cam_cy: 522.799224

cam_d0: -0.076160
cam_d1: 0.123001
cam_d2: -0.00113
cam_d3: 0.000251